-- liquibase formatted sql
-- changeset akislitcin:1
CREATE TABLE notification_task (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    message varchar(500) not null,
    date_time timestamp not null
);
